name: Publish

on:
  push:
    tags: [ v* ]

permissions:
  contents: read

env:
  DOTNET_VERSION: 10.0.x
  BUNDLE_PLATFORMS: x64|arm64

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Use MSBuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Update package manifest
      run: |
        [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq")
        $path = "src\WinQuickLook.Package\package.appxmanifest"
        $doc = [System.Xml.Linq.XDocument]::Load($path)
        $xName = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity"
        $doc.Root.Element($xName).Attribute("Version").Value = "${{ steps.setup_version.outputs.VERSION }}.0";
        $doc.Save($path)

    - name: Build application
      run: >
        msbuild .\src\WinQuickLook.slnx
        /Restore
        /p:Configuration=Release
        /p:Version="${{ steps.setup_version.outputs.VERSION }}"
        /p:UapAppxPackageBuildMode=StoreUpload
        /p:AppxBundlePlatforms="${{ env.BUNDLE_PLATFORMS }}"
        /p:AppxPackageDir=..\packed
        /p:AppxBundle=Always
        /p:AppxPackageSigningEnabled=false
        /p:PackageCertificateThumbprint=""
        /p:PublishReadyToRun=true
        /verbosity:minimal

    - name: Upload MSIX
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: msix
        path: packed\*.msixupload
